Resources:
  ImageProcessingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: resize_lambda.lambda_handler
      Role: arn:aws:iam::your-account-id:role/your-lambda-execution-role
      FunctionName: ImageProcessingLambda
      Code:
        S3Bucket: your-deployment-bucket
        S3Key: resize_lambda.zip
      Runtime: python3.8
